# Generated by Django 4.2.13 on 2024-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipl',
            fields=[
                ('iplid', models.AutoField(primary_key=True, serialize=False)),
                ('iplname', models.CharField(max_length=100)),
                ('ipllocation', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
