# Generated by Django 4.2.13 on 2024-07-19 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iplcolor',
            fields=[
                ('ipl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ipl')),
                ('dresscolor', models.CharField(max_length=20)),
            ],
            bases=('home.ipl',),
        ),
    ]
