version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      - http_proxy=http://your_proxy_server:your_proxy_port  # Adjust as per your proxy configuration
      - https_proxy=http://your_proxy_server:your_proxy_port  # Adjust as per your proxy configuration
    depends_on:
      - db  # Ensure that the 'db' service is started before the 'web' service

  db:
    image: postgres
    environment:
      POSTGRES_DB: vrg  # Change to your desired database name
      POSTGRES_USER: postgres  # Change to your desired database username
      POSTGRES_PASSWORD: vicky@123  # Change to your desired database password
    ports:
      - "5433:5432"  # Map container port 5432 to host port 5433 (if 5433 is available)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  vicky_network:
    driver: bridge
