# Generated by Django 3.2.23 on 2024-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactdetails', '0002_remove_vic_contactdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vic_contactdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vic_contactdetails',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
