# Generated by Django 3.2.23 on 2024-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vic_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_category', models.CharField(max_length=100)),
            ],
        ),
    ]
