# Generated by Django 3.2.23 on 2024-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vic_event',
            name='guests',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
