# Generated by Django 3.2.23 on 2024-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_vic_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vic_event',
            name='guests',
            field=models.CharField(default='', max_length=100),
        ),
    ]
