# Generated by Django 3.2.23 on 2024-03-13 15:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vic_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_news', models.TextField()),
                ('des', tinymce.models.HTMLField()),
            ],
        ),
    ]
