# Generated by Django 3.2.23 on 2024-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vic_news',
            name='icon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
