# Generated by Django 3.2.23 on 2024-03-21 15:56

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_vic_news_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_news', models.TextField()),
                ('des', tinymce.models.HTMLField()),
                ('vrg', autoslug.fields.AutoSlugField(editable=False, populate_from='today_news', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='vic_news',
        ),
    ]
