# Generated by Django 3.2.23 on 2024-03-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20240321_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vicnews',
            old_name='vrg',
            new_name='news_slug',
        ),
    ]
