# Generated by Django 3.2.23 on 2024-03-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_vrg_vicnews_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vicnews',
            name='news_slug',
        ),
    ]
