// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1721995872);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1721995872);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1721995902);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1721995872);
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1721995872);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240513132046");
user_pref("extensions.lastAppVersion", "115.11.0");
user_pref("extensions.lastPlatformVersion", "115.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"b423cc47-5d42-483b-830e-5d5b884e42cd\"}");
user_pref("idle.lastDailyNotification", 1721996027);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1721996027);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -13562);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1722009436);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1722009436);
user_pref("services.settings.thunderbird.search-config.last_check", 1722009436);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1722009436);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1721996027);
user_pref("toolkit.startup.last_success", 1721995841);
user_pref("toolkit.telemetry.cachedClientID", "422c9c3e-1ac5-40eb-9aed-4f467a78d67a");
user_pref("toolkit.telemetry.previousBuildID", "20240513132046");
