# Generated by Django 3.2.23 on 2024-04-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20240403_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
