# Generated by Django 3.2.23 on 2024-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vic_ipl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('location_no', models.TextField()),
                ('ipl_image', models.FileField(max_length=290, null=True, upload_to='ipl/')),
            ],
        ),
    ]
