# Generated by Django 3.2.23 on 2024-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vic_ipl',
            name='ipl_image',
            field=models.ImageField(default='', upload_to='ipl'),
        ),
    ]
