# Generated by Django 4.2.13 on 2024-07-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.student')),
                ('group', models.CharField(max_length=100)),
            ],
            bases=('core.student',),
        ),
    ]
