# Generated by Django 3.2.23 on 2024-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_icon', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=50)),
                ('project_des', models.TextField()),
            ],
        ),
    ]
