# Generated by Django 3.2.23 on 2024-02-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_des',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
