# Generated by Django 3.2.23 on 2024-02-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20240208_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='project_vic',
        ),
    ]
