# Generated by Django 3.2.23 on 2024-02-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_project_project_vic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_vic',
            name='another',
            field=models.TextField(default='your_default_value'),
        ),
    ]
