# Generated by Django 3.2.23 on 2024-02-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20240229_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_vic',
            name='founder',
            field=models.TextField(default='tera'),
        ),
    ]
