# Generated by Django 3.2.23 on 2024-02-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_vic_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_vic',
            name='vikash',
            field=models.TextField(default='kya'),
        ),
    ]
