# Generated by Django 4.2.13 on 2024-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('it', 'it'), ('non it', 'non it')], max_length=100),
        ),
    ]
